qhacks/qhacks-dashboard

.eslintrc, .gitignore, README.md, package-lock.json, package.json, server/controllers/api/auth.controller.js, server/controllers/api/user.controller.js, server/controllers/db.controller.js, server/controllers/index.controller.js, server/index.js, server/models/index.js, server/models/schemas/account.schema.js, server/routes/api/auth.router.js, server/routes/api/index.router.js, server/routes/api/user.router.js, server/routes/index.route.js, server/routes/index.router.js, server/services/authorization.js, server/services/custom-validator.js, server/services/token-utilities.js
Includes:
* Create a user account and receive an access token and refresh token after creation
* Get a new set of token when refreshing with a valid refresh token
* Get information for the currently authenticated user
* Update information for the currently authenticated user
=> Add basic account creation and authorization

package-lock.json, package.json
Uses `nsp` to check for any dependency security vulnerabilities
=> Add dependency vulnerability check

client/components/Login/Login.less
- 60-40 split for login screen columns
=> Change login screen from 50-50 to 60-40 split

client/HackerStore/HackerActions.js
*Fixes ticket #.*
- hot fix for apply issue
=> quick fix for apply not working

.circleci/config.yml
Should only deploy to stage on `dev` branch
=> Fix deployment filter

.circleci/config.yml
*Fixes ticket #.*
- adds sendgrid environment variables to ci
=> adding email specific environment variables to ci config

.circleci/config.yml
- Remove caching from CircleCI jobs. This is causing a ton of builds to fail.
=> Remove CircleCI caching

.circleci/config.yml, .gitignore, client/components/Dashboard/Dashboard.js, email/templates/application-successful.mjml, package-lock.json, package.json, server/mailer/index.js
*Fixes ticket #37.*
- Adds email build system
- Adds application successful email template
=> Add email templates

client/components/utils/ApplyForm.js, client/components/utils/LoginForm.js, client/components/utils/SemanticFormField.js
*Fixes ticket #.*
- fixes form field import issue
=> fixes form field import issue

package-lock.json, package.json, server/index.js
* Add `GET - /exception` endpoint to test on Google Cloud
=> Add Google Cloud error reporting middleware

package-lock.json, package.json, webpack.config.js
*Fixes ticket #.*
- adding prod plugins for optimization
=> adding production bundle optimizations into webpack config

CODE_OF_CONDUCT.md, CONTRIBUTING.md
*Fixes ticket #59.*
- Add code of conduct
- Add contributing guide
=> Satisfy GitHub community expectations

package-lock.json, package.json, server/index.js
Uses [helmet](https://helmetjs.github.io/) to improve HTTP header security
=> Add helmet to improve security headers

.circleci/config.yml, README.md, package-lock.json, package.json, server/index.js
fixes #53  
enviroment must be in production and FORCE_SSL must be set
=> adds ssl redirecting

server/models/userModel.js
=> hotfix/treat-emails-as-case-insensitive [master]

server/controllers/admin.controller.js
Fixes a typo in Golden ticket logic
=> Hotfix: Fix golden ticket [dev]

server/controllers/admin.controller.js
Fixes a typo in golden ticket logic
=> Hotfix: Fix golden ticket [master]

client/HackerStore/HackerActions.js, client/HackerStore/HackerReducer.js, client/components/Admin/Review.js, client/components/Admin/ReviewScale.js, server/api/v1/routes/admin.routes.js, server/controllers/admin.controller.js
* Allows admins to see rankings for users with completed applications
* Missing pagination on both client and server
=> Basic Application Review Table

server/models/userModel.js, server/strings/user.strings.js
* When updating people's RSVP move travelOrigin from UserSchema to Application
=> Add RSVP fields to UserSchema

client/components/Dashboard/Dashboard.js, client/components/Forms/RSVPForm.js, client/components/Hacker/ArriveInformation.js, client/components/Hacker/Landing.js, email/templates/application-accepted.mjml, package.json, server/api/v1/routes/user.routes.js, server/controllers/admin.controller.js, server/controllers/auth.controller.js, server/models/userModel.js
=> Release 1.3.0

packages/server/index.js
Fixes a small typo that wasn't caught in #133.
Fix the typo.
Because there is no other way!
Nope 😄 
- Fixes small typo when referencing the logger.
=> Fix logger typo in server

.github/CODEOWNERS
Adds code owners, now pull requests will automatically add reviewers based on the files the PR's touch. Plan is to add @rosslh as a code owner of the client package and @joeytepp as a code owner of the server stuff when they become more familiar. @RobertWSaunders is a code owner for the entire repo. 
Add the code owner file into the repo.
Increases code quality!
Nope 😄 
- Adds code owners into the repo.
=> Add code owners to the repo

.github/PULL_REQUEST_TEMPLATE.md
Noticed this little inconsistency when making my last PR. Up for debate, but thought it was worth addressing
=> Update PR template to use interrogative past tense

.circleci/config.yml, README.md
Update the CircleCI badge! After I renamed the repo to `qhacks-dashboard` the badge broke.
Take the new link from the CircleCI homepage!
Keep things up to date.
Nope!
- Update CircleCI badge.
- Formatting changes in `config.yml`
- Remove Jest badge.
=> Update CircleCI badge

.eslintrc, .prettierignore, .prettierrc, package.json, packages/server/controllers/admin.controller.js, packages/server/db/db.js
To improve our code formatting this change adds a new `format` script at the root of the project that will run our prettier options against the codebase. Note that this is supposed to act as a complement to our existing ESLint rules and fix simple errors for us. In addition to adding the script for manual usage this will also format your staged changes when you commit anything new to catch silly mistakes before they get committed.
I am planning on adding this to our other repositories, namely `qhacks-website`.
Add Prettier as a development dependency and the related configuration files.
Improves our code and increases developer productivity!
Nope! 
- Add Prettier as a dev dependency.
- Add Prettier configuration.
- Update some metadata for our project.
- Fixes some formatting issues that …
=> Add Prettier

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, packages/client/index.html, packages/email/templates/application-accepted-from-waitlist.mjml, packages/email/templates/application-accepted-reminder-after-waitlist-accepted.mjml, packages/email/templates/application-accepted-reminder.mjml, packages/email/templates/application-accepted.mjml, packages/server/index.js
Improve the documentation!
Wiki documentation to come soon 😃 
Write some documentation and update existing documentation.
Improve documentation for better context gathering!
Nope!
- Changes places that reference `Hacker Dashboard` to `QHacks Dashboard`.
- Improves our contributing guide to include some frequent issues we see in PRs.
- Improves our README with a more robust description of how to use the dashboard.
=> Improve documentation

package.json, packages/client/package.json, packages/server/__tests__/api/routes/auth.routes.test.js, packages/server/__tests__/api/routes/user.routes.test.js, packages/server/__tests__/config/test-framework.js, packages/server/__tests__/models/admin.model.test.js, packages/server/__tests__/models/event.model.test.js, packages/server/__tests__/models/hacker.model.test.js, packages/server/__tests__/models/settings.model.test.js, packages/server/__tests__/models/user.model.test.js, packages/server/package.json
Fixes: #141 
Add some more unit tests to the `server` package to get better coverage of all existing routes and models.
Added new unit tests to `auth` route, `Event` and `Settings` Model, also updated some test scripts.
Better coverage will allow us to change and add to existing functionality more safely!
Nope!
- New unit tests for remaining routes and models.
- Moved models tests into a more appropriate directory.
- Update stale test scripts.
=> Add tests to remaining routes and models

package.json, packages/client/package.json, packages/server/__tests__/config/test-framework.js, packages/server/controllers/admin.controller.js, packages/server/db/db.js, packages/server/index.js, packages/server/package.json
Update our dependencies and fix deprecation warnings when running the server! 
NOTE: I didn't really update client dependencies because we will need to do a big code clean based on future server contributions to be added soon. Therefore we can update dependencies then!
Update dependencies that needed updating and add things to fix warnings!
Keep things up to date and improve developer experience!
Nope!
- A couple of Mongoose changes to silence warnings!
- Updated dependencies where required!
- A few metadata changes!
=> Update dependencies and fix deprecation warnings

packages/server/db/models/user.js
Noticed an undefined error while testing authentication on the dashboard, so fixing it!
Changed `UserNotFoundError` (which does not exist) to `NotFoundError`
Better stability and error messages on the server
Nope
- Change `UserNotFoundError` to `NotFoundError`
=> Fix undefined error in User Model

packages/server/__tests__/config/test-framework.js, packages/server/__tests__/db/models/application.test.js, packages/server/__tests__/gql/resolvers/types/Application.test.js, packages/server/db/models/application.js, packages/server/db/models/event.js, packages/server/gql/resolvers/types/Application.js
Use our email library to send emails to Hackers when they apply!
Using the newly refactored `emails` package
To send some emails 📫 
No
- Add emails sending to `createApplication` mutation
- Fix some indexes on the DB
=> Add email sending to createApplication mutation

packages/client/components/App/App.js, packages/client/components/Apply/ApplicationForm.js, packages/client/components/Apply/Step2.js
Add link questions and make textareas only resizable in height
- Add link questions
- Make textareas only resizable in height
=> Add link questions

packages/server/gql/definitions/types/Hacker.graphql
Add schoolName field to hackerType
Updated GraphQL Schema
To improve the API
No
- Add `schoolName` field to `Hacker` type
=> Add schoolName field to hacker type

packages/client/components/Alert/Alert.js, packages/client/components/Apply/ApplicationForm.js, packages/client/components/ValidationError/ValidationError.js
=> Fix app submit and alerts

packages/client/components/Apply/ApplicationForm.js, packages/client/components/Apply/Step3.js, packages/client/components/Landing/ForgotPassword.js, packages/client/components/Landing/Login.js, packages/client/components/Landing/UpdatePassword.js
@joeytepp blessed us with some nice server errors!
Stuff!
-
-
-
=> Improve errors in ui

packages/client/components/Apply/ApplicationForm.js, packages/client/components/Apply/Step2.js, packages/client/components/Apply/Step3.js
=> Change linkedinlink to linkedinLink

packages/client/Client.js, packages/client/components/Alert/Alert.js, packages/client/components/Apply/Apply.js, packages/client/components/Dashboard/Card/Card.js, packages/client/components/Dashboard/Dashboard.js, packages/client/components/Dashboard/DashboardMenu.js, packages/client/components/Dashboard/DashboardSection/DashboardSection.js, packages/client/components/Dashboard/DashboardSection/Events.js, packages/client/components/Landing/ForgotPassword.js, packages/client/components/Landing/Login.js, packages/client/components/Landing/UpdatePassword.js, packages/client/index.html, packages/server/emails/templates/application-success.mjml, packages/server/emails/templates/reset-password-request.mjml, packages/server/emails/templates/reset-password-success.mjml
=> Small tweaks before launch

package.json, packages/client/package.json, packages/server/package.json
Launch version 2.0.0 of our server and client!
A lot of hard work! 😎 
Make our platform better and keep our code up to date!
Nope!
- Update the version of the overall project!
- Update the client version!
- Update the server version!
=> [dev] Release/v2.0.0

README.md
Update `README` so it is inline with the new changes we made in the rework
Fixes: #218
Made changes to the information in the `README` that was outdated.
To keep our docs up to date
No
- Update `README` to be consistent with new changes from rework
=> Make updates to README based on new rework

packages/server/gql/resolvers/types/Hacker.js
Fix the resolver for `hasApplied` on the `Hacker` type.
Change the resolver to check for a user's role instead of scopes.
More reliable than checking for scopes.
No
- Update `hasApplied` resolver
=> Fix hasApplied resolver

packages/server/gql/resolvers/types/Hacker.js
`hackerUpdate` to use role instead of scopes.
-
-
-
=> Change hackerUpdate resolver to use role instead of scopes
